// SAHA June 2026 recap galleries — two programs ran side by side:
//   summer/  Summer Camp, days 1–20 (16–20 pending photos — empty arrays
//            render as coming-soon tiles)
//   stem/    STEM Club, days 1–15 (no STEM on Fridays; day 15 = final day)
// pos = CSS object-position focal point so faces survive the tile crop.
// Regenerate/extend this file when new photos land.
export const SUMMER_DAYS = 20
export const STEM_DAYS = 15

export const SUMMER_GALLERIES = {
  day1: [
    { src: '/camp-gallery/summer/day1/1.webp', alt: 'SAHA Summer Camp — Day 1, photo 1' },
    { src: '/camp-gallery/summer/day1/2.webp', alt: 'SAHA Summer Camp — Day 1, photo 2' },
    { src: '/camp-gallery/summer/day1/3.webp', alt: 'SAHA Summer Camp — Day 1, photo 3' },
  ],
  day2: [
    { src: '/camp-gallery/summer/day2/1.webp', alt: 'SAHA Summer Camp — Day 2, photo 1' },
    { src: '/camp-gallery/summer/day2/2.webp', alt: 'SAHA Summer Camp — Day 2, photo 2' },
    { src: '/camp-gallery/summer/day2/3.webp', alt: 'SAHA Summer Camp — Day 2, photo 3' },
    { src: '/camp-gallery/summer/day2/4.webp', alt: 'SAHA Summer Camp — Day 2, photo 4' },
    { src: '/camp-gallery/summer/day2/5.webp', alt: 'SAHA Summer Camp — Day 2, photo 5' },
  ],
  day3: [
    { src: '/camp-gallery/summer/day3/1.webp', alt: 'SAHA Summer Camp — Day 3, photo 1' },
    { src: '/camp-gallery/summer/day3/2.webp', alt: 'SAHA Summer Camp — Day 3, photo 2' },
    { src: '/camp-gallery/summer/day3/3.webp', alt: 'SAHA Summer Camp — Day 3, photo 3' },
    { src: '/camp-gallery/summer/day3/4.webp', alt: 'SAHA Summer Camp — Day 3, photo 4' },
    { src: '/camp-gallery/summer/day3/5.webp', alt: 'SAHA Summer Camp — Day 3, photo 5' },
  ],
  day4: [
    { src: '/camp-gallery/summer/day4/1.webp', alt: 'SAHA Summer Camp — Day 4, photo 1' },
    { src: '/camp-gallery/summer/day4/2.webp', alt: 'SAHA Summer Camp — Day 4, photo 2' },
    { src: '/camp-gallery/summer/day4/3.webp', alt: 'SAHA Summer Camp — Day 4, photo 3' },
  ],
  day5: [
    { src: '/camp-gallery/summer/day5/1.webp', alt: 'SAHA Summer Camp — Day 5, photo 1' },
    { src: '/camp-gallery/summer/day5/2.webp', alt: 'SAHA Summer Camp — Day 5, photo 2' },
    { src: '/camp-gallery/summer/day5/3.webp', alt: 'SAHA Summer Camp — Day 5, photo 3' },
    { src: '/camp-gallery/summer/day5/4.webp', alt: 'SAHA Summer Camp — Day 5, photo 4' },
    { src: '/camp-gallery/summer/day5/5.webp', alt: 'SAHA Summer Camp — Day 5, photo 5', pos: '50% 8%' },
    { src: '/camp-gallery/summer/day5/6.webp', alt: 'SAHA Summer Camp — Day 5, photo 6' },
    { src: '/camp-gallery/summer/day5/7.webp', alt: 'SAHA Summer Camp — Day 5, photo 7' },
  ],
  day6: [
    { src: '/camp-gallery/summer/day6/1.webp', alt: 'SAHA Summer Camp — Day 6, photo 1' },
    { src: '/camp-gallery/summer/day6/2.webp', alt: 'SAHA Summer Camp — Day 6, photo 2' },
    { src: '/camp-gallery/summer/day6/3.webp', alt: 'SAHA Summer Camp — Day 6, photo 3' },
    { src: '/camp-gallery/summer/day6/4.webp', alt: 'SAHA Summer Camp — Day 6, photo 4' },
  ],
  day7: [
    { src: '/camp-gallery/summer/day7/1.webp', alt: 'SAHA Summer Camp — Day 7, photo 1' },
    { src: '/camp-gallery/summer/day7/2.webp', alt: 'SAHA Summer Camp — Day 7, photo 2' },
    { src: '/camp-gallery/summer/day7/3.webp', alt: 'SAHA Summer Camp — Day 7, photo 3' },
    { src: '/camp-gallery/summer/day7/4.webp', alt: 'SAHA Summer Camp — Day 7, photo 4' },
    { src: '/camp-gallery/summer/day7/5.webp', alt: 'SAHA Summer Camp — Day 7, photo 5' },
    { src: '/camp-gallery/summer/day7/6.webp', alt: 'SAHA Summer Camp — Day 7, photo 6' },
    { src: '/camp-gallery/summer/day7/7.webp', alt: 'SAHA Summer Camp — Day 7, photo 7' },
    { src: '/camp-gallery/summer/day7/8.webp', alt: 'SAHA Summer Camp — Day 7, photo 8' },
    { src: '/camp-gallery/summer/day7/9.webp', alt: 'SAHA Summer Camp — Day 7, photo 9' },
    { src: '/camp-gallery/summer/day7/10.webp', alt: 'SAHA Summer Camp — Day 7, photo 10' },
  ],
  day8: [
    { src: '/camp-gallery/summer/day8/1.webp', alt: 'SAHA Summer Camp — Day 8, photo 1' },
    { src: '/camp-gallery/summer/day8/2.webp', alt: 'SAHA Summer Camp — Day 8, photo 2' },
    { src: '/camp-gallery/summer/day8/3.webp', alt: 'SAHA Summer Camp — Day 8, photo 3' },
    { src: '/camp-gallery/summer/day8/4.webp', alt: 'SAHA Summer Camp — Day 8, photo 4' },
    { src: '/camp-gallery/summer/day8/5.webp', alt: 'SAHA Summer Camp — Day 8, photo 5' },
    { src: '/camp-gallery/summer/day8/6.webp', alt: 'SAHA Summer Camp — Day 8, photo 6' },
  ],
  day9: [
    { src: '/camp-gallery/summer/day9/1.webp', alt: 'SAHA Summer Camp — Day 9, photo 1' },
    { src: '/camp-gallery/summer/day9/2.webp', alt: 'SAHA Summer Camp — Day 9, photo 2' },
    { src: '/camp-gallery/summer/day9/3.webp', alt: 'SAHA Summer Camp — Day 9, photo 3' },
    { src: '/camp-gallery/summer/day9/4.webp', alt: 'SAHA Summer Camp — Day 9, photo 4' },
    { src: '/camp-gallery/summer/day9/5.webp', alt: 'SAHA Summer Camp — Day 9, photo 5' },
  ],
  day10: [
    { src: '/camp-gallery/summer/day10/1.webp', alt: 'SAHA Summer Camp — Day 10, photo 1' },
    { src: '/camp-gallery/summer/day10/2.webp', alt: 'SAHA Summer Camp — Day 10, photo 2' },
    { src: '/camp-gallery/summer/day10/3.webp', alt: 'SAHA Summer Camp — Day 10, photo 3', pos: '50% 10%' },
  ],
  day11: [
    { src: '/camp-gallery/summer/day11/1.webp', alt: 'SAHA Summer Camp — Day 11, photo 1' },
    { src: '/camp-gallery/summer/day11/2.webp', alt: 'SAHA Summer Camp — Day 11, photo 2' },
    { src: '/camp-gallery/summer/day11/3.webp', alt: 'SAHA Summer Camp — Day 11, photo 3' },
    { src: '/camp-gallery/summer/day11/4.webp', alt: 'SAHA Summer Camp — Day 11, photo 4' },
    { src: '/camp-gallery/summer/day11/5.webp', alt: 'SAHA Summer Camp — Day 11, photo 5' },
    { src: '/camp-gallery/summer/day11/6.webp', alt: 'SAHA Summer Camp — Day 11, photo 6' },
    { src: '/camp-gallery/summer/day11/7.webp', alt: 'SAHA Summer Camp — Day 11, photo 7' },
  ],
  day12: [
    { src: '/camp-gallery/summer/day12/1.webp', alt: 'SAHA Summer Camp — Day 12, photo 1' },
    { src: '/camp-gallery/summer/day12/2.webp', alt: 'SAHA Summer Camp — Day 12, photo 2' },
    { src: '/camp-gallery/summer/day12/3.webp', alt: 'SAHA Summer Camp — Day 12, photo 3' },
    { src: '/camp-gallery/summer/day12/4.webp', alt: 'SAHA Summer Camp — Day 12, photo 4' },
    { src: '/camp-gallery/summer/day12/5.webp', alt: 'SAHA Summer Camp — Day 12, photo 5' },
    { src: '/camp-gallery/summer/day12/6.webp', alt: 'SAHA Summer Camp — Day 12, photo 6' },
    { src: '/camp-gallery/summer/day12/7.webp', alt: 'SAHA Summer Camp — Day 12, photo 7' },
    { src: '/camp-gallery/summer/day12/8.webp', alt: 'SAHA Summer Camp — Day 12, photo 8' },
    { src: '/camp-gallery/summer/day12/9.webp', alt: 'SAHA Summer Camp — Day 12, photo 9' },
    { src: '/camp-gallery/summer/day12/10.webp', alt: 'SAHA Summer Camp — Day 12, photo 10' },
  ],
  day13: [
    { src: '/camp-gallery/summer/day13/1.webp', alt: 'SAHA Summer Camp — Day 13, photo 1' },
    { src: '/camp-gallery/summer/day13/2.webp', alt: 'SAHA Summer Camp — Day 13, photo 2' },
    { src: '/camp-gallery/summer/day13/3.webp', alt: 'SAHA Summer Camp — Day 13, photo 3' },
    { src: '/camp-gallery/summer/day13/4.webp', alt: 'SAHA Summer Camp — Day 13, photo 4' },
    { src: '/camp-gallery/summer/day13/5.webp', alt: 'SAHA Summer Camp — Day 13, photo 5' },
  ],
  day14: [
    { src: '/camp-gallery/summer/day14/1.webp', alt: 'SAHA Summer Camp — Day 14, photo 1' },
    { src: '/camp-gallery/summer/day14/2.webp', alt: 'SAHA Summer Camp — Day 14, photo 2' },
    { src: '/camp-gallery/summer/day14/3.webp', alt: 'SAHA Summer Camp — Day 14, photo 3' },
    { src: '/camp-gallery/summer/day14/4.webp', alt: 'SAHA Summer Camp — Day 14, photo 4' },
    { src: '/camp-gallery/summer/day14/5.webp', alt: 'SAHA Summer Camp — Day 14, photo 5' },
    { src: '/camp-gallery/summer/day14/6.webp', alt: 'SAHA Summer Camp — Day 14, photo 6' },
    { src: '/camp-gallery/summer/day14/7.webp', alt: 'SAHA Summer Camp — Day 14, photo 7' },
    { src: '/camp-gallery/summer/day14/8.webp', alt: 'SAHA Summer Camp — Day 14, photo 8' },
    { src: '/camp-gallery/summer/day14/9.webp', alt: 'SAHA Summer Camp — Day 14, photo 9' },
    { src: '/camp-gallery/summer/day14/10.webp', alt: 'SAHA Summer Camp — Day 14, photo 10' },
    { src: '/camp-gallery/summer/day14/11.webp', alt: 'SAHA Summer Camp — Day 14, photo 11' },
    { src: '/camp-gallery/summer/day14/12.webp', alt: 'SAHA Summer Camp — Day 14, photo 12' },
  ],
  day15: [
    { src: '/camp-gallery/summer/day15/1.webp', alt: 'SAHA Summer Camp — Day 15, photo 1' },
    { src: '/camp-gallery/summer/day15/2.webp', alt: 'SAHA Summer Camp — Day 15, photo 2' },
    { src: '/camp-gallery/summer/day15/3.webp', alt: 'SAHA Summer Camp — Day 15, photo 3' },
    { src: '/camp-gallery/summer/day15/4.webp', alt: 'SAHA Summer Camp — Day 15, photo 4' },
    { src: '/camp-gallery/summer/day15/5.webp', alt: 'SAHA Summer Camp — Day 15, photo 5' },
    { src: '/camp-gallery/summer/day15/6.webp', alt: 'SAHA Summer Camp — Day 15, photo 6' },
    { src: '/camp-gallery/summer/day15/7.webp', alt: 'SAHA Summer Camp — Day 15, photo 7' },
    { src: '/camp-gallery/summer/day15/8.webp', alt: 'SAHA Summer Camp — Day 15, photo 8', pos: '50% 12%' },
    { src: '/camp-gallery/summer/day15/9.webp', alt: 'SAHA Summer Camp — Day 15, photo 9' },
    { src: '/camp-gallery/summer/day15/10.webp', alt: 'SAHA Summer Camp — Day 15, photo 10' },
  ],
  day16: [],
  day17: [],
  day18: [],
  day19: [],
  day20: [],
}

export const STEM_GALLERIES = {
  day1: [
    { src: '/camp-gallery/stem/day1/1.webp', alt: 'SAHA STEM Club — Day 1, photo 1', pos: '50% 8%' },
    { src: '/camp-gallery/stem/day1/2.webp', alt: 'SAHA STEM Club — Day 1, photo 2' },
    { src: '/camp-gallery/stem/day1/3.webp', alt: 'SAHA STEM Club — Day 1, photo 3', pos: '50% 12%' },
    { src: '/camp-gallery/stem/day1/4.webp', alt: 'SAHA STEM Club — Day 1, photo 4', pos: '50% 12%' },
  ],
  day2: [
    { src: '/camp-gallery/stem/day2/1.webp', alt: 'SAHA STEM Club — Day 2, photo 1' },
    { src: '/camp-gallery/stem/day2/2.webp', alt: 'SAHA STEM Club — Day 2, photo 2' },
    { src: '/camp-gallery/stem/day2/3.webp', alt: 'SAHA STEM Club — Day 2, photo 3' },
    { src: '/camp-gallery/stem/day2/4.webp', alt: 'SAHA STEM Club — Day 2, photo 4', pos: '50% 25%' },
  ],
  day3: [
    { src: '/camp-gallery/stem/day3/1.webp', alt: 'SAHA STEM Club — Day 3, photo 1' },
    { src: '/camp-gallery/stem/day3/2.webp', alt: 'SAHA STEM Club — Day 3, photo 2' },
  ],
  day4: [
    { src: '/camp-gallery/stem/day4/1.webp', alt: 'SAHA STEM Club — Day 4, photo 1' },
    { src: '/camp-gallery/stem/day4/2.webp', alt: 'SAHA STEM Club — Day 4, photo 2', pos: '50% 0%' },
    { src: '/camp-gallery/stem/day4/3.webp', alt: 'SAHA STEM Club — Day 4, photo 3', pos: '50% 12%' },
    { src: '/camp-gallery/stem/day4/4.webp', alt: 'SAHA STEM Club — Day 4, photo 4' },
  ],
  day5: [
    { src: '/camp-gallery/stem/day5/1.webp', alt: 'SAHA STEM Club — Day 5, photo 1' },
  ],
  day6: [
    { src: '/camp-gallery/stem/day6/1.webp', alt: 'SAHA STEM Club — Day 6, photo 1' },
    { src: '/camp-gallery/stem/day6/2.webp', alt: 'SAHA STEM Club — Day 6, photo 2', pos: '50% 28%' },
    { src: '/camp-gallery/stem/day6/3.webp', alt: 'SAHA STEM Club — Day 6, photo 3' },
    { src: '/camp-gallery/stem/day6/4.webp', alt: 'SAHA STEM Club — Day 6, photo 4' },
    { src: '/camp-gallery/stem/day6/5.webp', alt: 'SAHA STEM Club — Day 6, photo 5' },
  ],
  day7: [
    { src: '/camp-gallery/stem/day7/1.webp', alt: 'SAHA STEM Club — Day 7, photo 1' },
    { src: '/camp-gallery/stem/day7/2.webp', alt: 'SAHA STEM Club — Day 7, photo 2', pos: '50% 18%' },
    { src: '/camp-gallery/stem/day7/3.webp', alt: 'SAHA STEM Club — Day 7, photo 3', pos: '50% 15%' },
    { src: '/camp-gallery/stem/day7/4.webp', alt: 'SAHA STEM Club — Day 7, photo 4' },
  ],
  day8: [
    { src: '/camp-gallery/stem/day8/1.webp', alt: 'SAHA STEM Club — Day 8, photo 1' },
    { src: '/camp-gallery/stem/day8/2.webp', alt: 'SAHA STEM Club — Day 8, photo 2', pos: '50% 22%' },
    { src: '/camp-gallery/stem/day8/3.webp', alt: 'SAHA STEM Club — Day 8, photo 3' },
    { src: '/camp-gallery/stem/day8/4.webp', alt: 'SAHA STEM Club — Day 8, photo 4' },
  ],
  day9: [
    { src: '/camp-gallery/stem/day9/1.webp', alt: 'SAHA STEM Club — Day 9, photo 1' },
    { src: '/camp-gallery/stem/day9/2.webp', alt: 'SAHA STEM Club — Day 9, photo 2' },
    { src: '/camp-gallery/stem/day9/3.webp', alt: 'SAHA STEM Club — Day 9, photo 3' },
    { src: '/camp-gallery/stem/day9/4.webp', alt: 'SAHA STEM Club — Day 9, photo 4', pos: '50% 30%' },
    { src: '/camp-gallery/stem/day9/5.webp', alt: 'SAHA STEM Club — Day 9, photo 5' },
  ],
  day10: [
    { src: '/camp-gallery/stem/day10/1.webp', alt: 'SAHA STEM Club — Day 10, photo 1' },
    { src: '/camp-gallery/stem/day10/2.webp', alt: 'SAHA STEM Club — Day 10, photo 2', pos: '50% 55%' },
    { src: '/camp-gallery/stem/day10/3.webp', alt: 'SAHA STEM Club — Day 10, photo 3' },
    { src: '/camp-gallery/stem/day10/4.webp', alt: 'SAHA STEM Club — Day 10, photo 4' },
  ],
  day11: [
    { src: '/camp-gallery/stem/day11/1.webp', alt: 'SAHA STEM Club — Day 11, photo 1' },
    { src: '/camp-gallery/stem/day11/2.webp', alt: 'SAHA STEM Club — Day 11, photo 2' },
    { src: '/camp-gallery/stem/day11/3.webp', alt: 'SAHA STEM Club — Day 11, photo 3', pos: '50% 12%' },
    { src: '/camp-gallery/stem/day11/4.webp', alt: 'SAHA STEM Club — Day 11, photo 4' },
    { src: '/camp-gallery/stem/day11/5.webp', alt: 'SAHA STEM Club — Day 11, photo 5', pos: '50% 15%' },
    { src: '/camp-gallery/stem/day11/6.webp', alt: 'SAHA STEM Club — Day 11, photo 6' },
    { src: '/camp-gallery/stem/day11/7.webp', alt: 'SAHA STEM Club — Day 11, photo 7', pos: '50% 10%' },
    { src: '/camp-gallery/stem/day11/8.webp', alt: 'SAHA STEM Club — Day 11, photo 8' },
  ],
  day12: [
    { src: '/camp-gallery/stem/day12/1.webp', alt: 'SAHA STEM Club — Day 12, photo 1' },
    { src: '/camp-gallery/stem/day12/2.webp', alt: 'SAHA STEM Club — Day 12, photo 2' },
    { src: '/camp-gallery/stem/day12/3.webp', alt: 'SAHA STEM Club — Day 12, photo 3' },
    { src: '/camp-gallery/stem/day12/4.webp', alt: 'SAHA STEM Club — Day 12, photo 4', pos: '50% 15%' },
    { src: '/camp-gallery/stem/day12/5.webp', alt: 'SAHA STEM Club — Day 12, photo 5', pos: '50% 18%' },
  ],
  day13: [
    { src: '/camp-gallery/stem/day13/1.webp', alt: 'SAHA STEM Club — Day 13, photo 1' },
    { src: '/camp-gallery/stem/day13/2.webp', alt: 'SAHA STEM Club — Day 13, photo 2' },
    { src: '/camp-gallery/stem/day13/3.webp', alt: 'SAHA STEM Club — Day 13, photo 3' },
  ],
  day14: [
    { src: '/camp-gallery/stem/day14/1.webp', alt: 'SAHA STEM Club — Day 14, photo 1' },
    { src: '/camp-gallery/stem/day14/2.webp', alt: 'SAHA STEM Club — Day 14, photo 2', pos: '50% 5%' },
  ],
  day15: [
    { src: '/camp-gallery/stem/day15/1.webp', alt: 'SAHA STEM Club — Day 15, photo 1' },
    { src: '/camp-gallery/stem/day15/2.webp', alt: 'SAHA STEM Club — Day 15, photo 2', pos: '50% 20%' },
    { src: '/camp-gallery/stem/day15/3.webp', alt: 'SAHA STEM Club — Day 15, photo 3' },
  ],
}
