// bcryptjs is the pure-JS port of bcrypt. Same `$2a$` / `$2b$` hash format —
// hashes generated by either library cross-verify cleanly, so existing admin
// password hashes keep working. Trade: ~30% slower verify than the native lib,
// which is invisible at our scale (a handful of admin logins per day) and saves
// ~90 seconds on every cold Railway build by skipping the node-gyp compile.
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'

const BCRYPT_ROUNDS = 12
const JWT_ALGORITHM = 'HS256'

// 30-day session per spec.
const SESSION_TTL_SECONDS = 60 * 60 * 24 * 30

export interface JwtPayload {
  userId: number
  email: string
}

function getJwtSecret(): string {
  const secret = process.env.JWT_SECRET
  if (!secret || secret.length < 32) {
    throw new Error('[auth] JWT_SECRET must be set to a value of at least 32 characters.')
  }
  return secret
}

export async function hashPassword(plain: string): Promise<string> {
  return bcrypt.hash(plain, BCRYPT_ROUNDS)
}

export async function verifyPassword(plain: string, hash: string): Promise<boolean> {
  return bcrypt.compare(plain, hash)
}

export function signSession(payload: JwtPayload): string {
  return jwt.sign(payload, getJwtSecret(), {
    algorithm: JWT_ALGORITHM,
    expiresIn: SESSION_TTL_SECONDS,
  })
}

export function verifySession(token: string): JwtPayload | null {
  try {
    const decoded = jwt.verify(token, getJwtSecret(), { algorithms: [JWT_ALGORITHM] })
    if (typeof decoded === 'string') return null
    const { userId, email } = decoded as Record<string, unknown>
    if (typeof userId !== 'number' || typeof email !== 'string') return null
    return { userId, email }
  } catch {
    return null
  }
}

export const SESSION_COOKIE_NAME = 'saha_session'

export const sessionCookieOptions = {
  httpOnly: true,
  secure: process.env.NODE_ENV === 'production',
  sameSite: 'lax' as const,
  maxAge: SESSION_TTL_SECONDS * 1000,
  path: '/',
}

export const clearSessionCookieOptions = {
  ...sessionCookieOptions,
  maxAge: 0,
}

// ---------- Student sessions ----------
// Self-service student accounts use a SEPARATE cookie + JWT from the admin.
// Two guards against cross-use:
//   1. Different cookie name (saha_student vs saha_session), so a student
//      session is never sent to an admin endpoint and vice versa.
//   2. A `type: 'student'` claim in the JWT, verified on read — even if a
//      token were placed in the wrong cookie, the type check rejects it.

export interface StudentJwtPayload {
  studentId: number
  email: string
}

export const STUDENT_COOKIE_NAME = 'saha_student'

export function signStudentSession(payload: StudentJwtPayload): string {
  return jwt.sign({ ...payload, type: 'student' }, getJwtSecret(), {
    algorithm: JWT_ALGORITHM,
    expiresIn: SESSION_TTL_SECONDS,
  })
}

export function verifyStudentSession(token: string): StudentJwtPayload | null {
  try {
    const decoded = jwt.verify(token, getJwtSecret(), { algorithms: [JWT_ALGORITHM] })
    if (typeof decoded === 'string') return null
    const { studentId, email, type } = decoded as Record<string, unknown>
    if (type !== 'student') return null
    if (typeof studentId !== 'number' || typeof email !== 'string') return null
    return { studentId, email }
  } catch {
    return null
  }
}
